### ISSUE TITLE
Missing option to specify version of chart to run against

### ISSUE THREAD

**Issue by herrbpl** [nikhilsbhat/helm-drift#18]
When using helm drift against chart and not release, it automatically takes latest chart in repo to check against.

for example:
`helm drift run -n test-bo02-ca-02 test-bo02 repo/clientarea  --skip-validation -f ../values-terragrunt-plan.yaml `
would take latest chart of `clientarea` from repo `repo` and check against that.

In operational environments, it is often required to check againt some devel version or maybe little bit older version than latest in repo.

As workaround, one can fetch and unpack desired chart version into subfolder but this is extra step.

Please consider adding --version option for helm drift plugin

**Comment by nikhilsbhat** [comment]
@herrbpl, Make sense to add the support for it and this [`commit`](https://github.com/nikhilsbhat/helm-drift/commit/c74b55821599af9331eb667aea5f4da8a6366e3e#diff-fc980e4908d816df7494073bccda36b73ecd74d03da6780adfa938e55fc7ed2eR52) has necessary changes.

The latest release will have the necessary support, hence closing this.
