### ISSUE TITLE
Target older chart version

### ISSUE THREAD

**Issue by lusitania** [nikhilsbhat/helm-drift#25]
How do you determine drift from a specific version of a helm chart and not the newest?

**Comment by nikhilsbhat** [comment]
@lusitania, are you referring to version or revision? If it's version, the plugin already supports it; you just need to set `--version`. 
For more information, refer to all available plugin flags [here](https://github.com/nikhilsbhat/helm-drift/blob/main/docs/doc/drift.md)."
