### ISSUE TITLE
Does concurency work?

### ISSUE THREAD

**Issue by markretallack** [nikhilsbhat/helm-drift#30]
Hi, 
I have found that for complex charts, it can start up multiple kubectl diff commands, the concurency option does not seem to restrict this.

**Comment by nikhilsbhat** [comment]
@markretallack, if you're referring to the `--concurrency` flag in the plugin, it only configures the argument `--concurrency` of `kubectl diff` and doesn't control the number of `kubectl` processes initiated by the plugin itself.

**Comment by markretallack** [comment]
@nikhilsbhat, Thanks for the reply. 

What I am seeing is that when I run helm-diff, it starts up a number of kubectl command simultaneously. This can be 100+ and in our CI pipeline this is causing issues (hitting resource limits).  

I have a quick look at the code and I think the following section runs the command:

https://github.com/nikhilsbhat/helm-drift/blob/1b4f293899ae8b298b339ffb3494abeb879900da/pkg/diff.go#L35

I dont know much about go, but is it running the kubectl command at the same time or in sequence? I think its using goroutines and wait groups, is there a limit set on this?

**Comment by nikhilsbhat** [comment]
The current version of the code doesn't impose a limit on the threads spawned by the plugin. I haven't encountered a use case before where managing such a large number of resources hits the resource limit. I'll take this feedback into account and work on addressing it.
